<?php

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemList;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\TypedData\DataDefinitionInterface;
use Drupal\geocoder\Plugin\Geocoder\Formatter;
use Drupal\taxonomy\Entity\Term;
use Geocoder\Location;
use Drupal\mapbox_field\Plugin\Field\FieldType\MapboxField;
use Drupal\mapbox\Mapbox;
use Drupal\rdasa_mapping\Controller\RDA_mapping;


function rdasa_mapping_form_alter(&$form, FormStateInterface $form_state) {
  $tt = "ss";
}

function rdasa_mapping_form_node_project_edit_form_alter(&$form, FormStateInterface $form_state) {
  $form["field_address_string"]["widget"][0]["#disabled"] = true;
  $form['actions']['submit']['#submit'][] = '_rdasa_mapping_form_node_project_submit';
}


/**
 * Submit callback for user profile form to save the Google Analytics setting.
 */
function _rdasa_mapping_form_node_project_submit($form, FormStateInterface $form_state) {
  /** @var Drupal\user\ProfileForm $profileForm */
  $projectForm = $form_state->getFormObject();
  /** @var Drupal\user\Entity\User $account */
  $project = $projectForm->getEntity();
  // save first so I have a definition to edit!

  // @TODO Only if changed
  // @TODO also need to check if it exists
  $field_address = $project->field_address[0];

  $address=$field_address->getValue();
  $geocoder = \Drupal::service("geocoder");
  $address_service = \Drupal::service("geocoder_address.address");
  $rda_mapper = new RDA_mapping;
  $coordinates = $rda_mapper->addressStringToLocation($address);
  if (!empty($coordinates)) {
    $latitude = number_format($coordinates->getLatitude(), 10);
    $longitude = number_format($coordinates->getLongitude(), 10);
    $project_location = $project->get("field_project_location");
    if (!empty($project_location)) {
      $pl = $project_location->getValue();
      $pl[0]["lng"] = $longitude;
      $pl[0]["lat"] = $latitude;
      $project->set("field_project_location", $pl);
    } else {
      $project->set("field_project_location", [$latitude, $longitude]);
    }
  }
  /**
  $location = $project->field_project_location;
  // When updating   $field_project_location = $project->field_project_location->first();
  // When not updating;
  **/
  $project->save();
}

function rdasa_mapping_preprocess_container(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  // view.projects_map.page_2
  if ($route_name == "entity.group.canonical" && $id == "views_block__projects_map_block_1") {
    $mapbox_service = \Drupal::service('mapbox');
    $mapbox_key = $mapbox_service->accessToken();
    $variables["mapbox"]["id"] = $mapbox_key;
    // Get this Mapboxes GeoFeatures from the view
    $geofeatures_view = $variables["content"]["#view"];
    $results = $geofeatures_view->result;
    $coordinates = array();
    foreach($results as $result) {
      $project = $result->_entity;
      $geofeature = $project->field_project_location->getValue();
      if(!empty($geofeature)) {
        $lat = (float)$geofeature[0]["lat"];
        $lng = (float)$geofeature[0]["lng"];
        $titleItem = $project->title->getValue();
        $title = $titleItem[0]["value"];
        $nodeid = $project->id();
        $business_name = "";
        $business_name_item = $project->field_business_name->getValue();
        if (!empty($business_name_item)) {
          $business_name = $business_name_item[0]["value"];
        }
        $project_description = "";
        $project_description_item = $project->field_project_description->getValue();
        if(!empty($project_description_item)) {
          $project_description = _filter_html_escape($project_description_item[0]["value"]);
        }
        $project_locality_item = $project->field_project_locality->getValue();
        if(!empty($project_locality_item)) {
          $project_locality = $project_locality_item[0]["value"];
        } else {
          $project_locality = "";
        }
        $project_address_item = $project->field_address_string->getValue();
        if(!empty($project_address_item)) {
          $project_address = $project_address_item[0]["value"];
        }
        $lga = "";
        $project_lga_item = $project->field_local_government_area->getValue();
        if(!empty($project_lga_item)) {
          $lga_id = $project_lga_item[0]["target_id"];
          if (!empty($lga_id)) {
            $term = Term::load($lga_id);
            $lga = $term->getName();
          }
        }
        $description = <<<EOF
 <strong><a href='/node/$nodeid'>$title</a></strong><p>
 <ul>
 <li>Business name: $business_name</li>
 <li>Project description: $project_description</li>
 <li> LGA: $lga</li>
 <li>Locality: $project_locality</li>
 <li>Address: $project_address</li>
 </ul>
 </p>
 EOF;
        $description = str_replace(PHP_EOL,'', $description);
        $public = $project->field_public_project->getValue();
        $public =  ($public[0]["value"] == 1) ? "Yes" : 'No';

        $coordinates[] = [$lat, $lng, $title, $description, $public];
      }
    }
    $variables["mapbox"]["coordinates"] = $coordinates;

    $tt="ss";
  }}


function rdasa_mapping_preprocess_views_view(&$variables) {
  $view = $variables["view"];
  $id = $view->id();
  $display = $view->current_display;
  if ($id == "projects_map" && $display =="page_2") {
    $mapbox_service = \Drupal::service('mapbox');
    $mapbox_key = $mapbox_service->accessToken();
    $variables["mapbox"]["id"] = $mapbox_key;
    // Get this Mapboxes GeoFeatures from the view
    $results = $view->result;
    $coordinates = [];
    foreach ($results as $key => $result) {
      $project = $result->_entity;
      $geofeature = $project->field_project_location->getValue();
      if (!empty($geofeature)) {
        $lat = (float) $geofeature[0]["lat"];
        $lng = (float) $geofeature[0]["lng"];
        $titleItem = $project->title->getValue();
        $title = $titleItem[0]["value"];
        $nodeid = $project->id();
        $business_name = "";
        $business_name_item = $project->field_business_name->getValue();
        if (!empty($business_name_item)) {
          $business_name = $business_name_item[0]["value"];
        }
        $project_description = "";
        $project_description_item = $project->field_project_description->getValue();
        if (!empty($project_description_item)) {
          $project_description = _filter_html_escape($project_description_item[0]["value"]);
        }
        $project_locality_item = $project->field_project_locality->getValue();
        if (!empty($project_locality_item)) {
          $project_locality = $project_locality_item[0]["value"];
        }
        else {
          $project_locality = "";
        }
        $project_address_item = $project->field_address_string->getValue();
        if (!empty($project_address_item)) {
          $project_address = $project_address_item[0]["value"];
        }
        $lga = "";
        $project_lga_item = $project->field_local_government_area->getValue();
        if (!empty($project_lga_item)) {
          $lga_id = $project_lga_item[0]["target_id"];
          if (!empty($lga_id)) {
            $term = Term::load($lga_id);
            $lga = $term->getName();
          }
        }
        $description = <<<EOF
 <strong><a href='/node/$nodeid'>$title</a></strong><p>
 <ul>
 <li>Business name: $business_name</li>
 <li>Project description: $project_description</li>
 <li> LGA: $lga</li>
 <li>Locality: $project_locality</li>
 <li>Address: $project_address</li>
 </ul>
 </p>
 EOF;
        $description = str_replace(PHP_EOL, '', $description);
        $public = $project->field_public_project->getValue();
        $public = ($public[0]["value"] == 1) ? "Yes" : 'No';
        $row_number= $key + 1;
        $coordinates[] = [$lat, $lng, $title, $description, $public, $row_number];
      }
    }
    $variables["mapbox"]["coordinates"] = $coordinates;
  }
}


function rdasa_mapping_preprocess_block(&$variables) {
  $id = $variables["elements"]["#id"];
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == "entity.group.canonical" && $id == "views_block__projects_map_block_1") {
    $mapbox_service = \Drupal::service('mapbox');
    $mapbox_key = $mapbox_service->accessToken();
    $variables["mapbox"]["id"] = $mapbox_key;
    // Get this Mapboxes GeoFeatures from the view
    $geofeatures_view = $variables["content"]["#view"];
    $results = $geofeatures_view->result;
    $coordinates = array();
    foreach($results as $result) {
      $project = $result->_entity;
      $geofeature = $project->field_project_location->getValue();
      if(!empty($geofeature)) {
        $lat = (float)$geofeature[0]["lat"];
        $lng = (float)$geofeature[0]["lng"];
        $titleItem = $project->title->getValue();
        $title = $titleItem[0]["value"];
        $nodeid = $project->id();
        $business_name = "";
        $business_name_item = $project->field_business_name->getValue();
        if (!empty($business_name_item)) {
         $business_name = $business_name_item[0]["value"];
        }
        $project_description = "";
        $project_description_item = $project->field_project_description->getValue();
        if(!empty($project_description_item)) {
          $project_description = _filter_html_escape($project_description_item[0]["value"]);
        }
        $project_locality_item = $project->field_project_locality->getValue();
        if(!empty($project_locality_item)) {
          $project_locality = $project_locality_item[0]["value"];
        } else {
          $project_locality = "";
        }
        $project_address_item = $project->field_address_string->getValue();
        if(!empty($project_address_item)) {
          $project_address = $project_address_item[0]["value"];
        }
        $lga = "";
        $project_lga_item = $project->field_local_government_area->getValue();
        if(!empty($project_lga_item)) {
          $lga_id = $project_lga_item[0]["target_id"];
          if (!empty($lga_id)) {
            $term = Term::load($lga_id);
            $lga = $term->getName();
          }
        }
        $description = <<<EOF
 <strong><a href='/node/$nodeid'>$title</a></strong><p>
 <ul>
 <li>Business name: $business_name</li>
 <li>Project description: $project_description</li>
 <li> LGA: $lga</li>
 <li>Locality: $project_locality</li>
 <li>Address: $project_address</li>
 </ul>
 </p>
 EOF;
        $description = str_replace(PHP_EOL,'', $description);
        $public = $project->field_public_project->getValue();
        $public =  ($public[0]["value"] == 1) ? "Yes" : 'No';

        $coordinates[] = [$lat, $lng, $title, $description, $public];
      }
    }
    $variables["mapbox"]["coordinates"] = $coordinates;

    $tt="ss";
  }
}
function rdasa_mapping_preprocess_page(&$variables): void
{

  if(array_key_exists("node",$variables)) {
    $type = $variables["node"]->getType();
    if ($type == "project") {
      $tt = "ss";

    }
  }
  $viewport = [
    '#tag' => 'meta',
    '#attributes' => [
      'name' => 'viewport',
      'content' => 'initial-scale=1,maximum-scale=1,user-scalable=no',
    ],
  ];

  $variables['#attached']['library'][] =  'rdasa_mapping/mapbox';
  $variables['page']['#attached']['html_head'][] = [$viewport, 'viewport'];
}


/**
 * Implements hook_theme().
 */
function rdasa_mapping_theme()
{
  return array('block__views_block__projects_map_block_1' => [
    'variables' => [
      'mapbox' => []
    ],
    'template' => 'block--views-block--projects-map-block-1',
    'base hook' => 'block__views',
  ],
    'views_view__projects_map' => [
      'template' => 'views-view-projects-map',
      'base hook' => 'views__view']);
  /**
   *
   * page__group__group_map

  return array(
    'views_view_unformatted_projects_map' => [
      'variables' => [
        'mapbox' => NULL,
      ],
      'template' => 'views-view-unformatted-projects-map',
      'base hook' => 'views_view_unformatted',
    ],
    'views_view_fields_projects_map' => [
      'variables' => [
        'mapbox' => NULL
      ],
      'template' => 'views-view-fields-projects-map',
      'base hook' => 'views_view_fields',
    ],

    'mapbox_field' => [
      'variables' => [
        'mapbox' => NULL
      ],
      'template' => 'mapbox-field',
      'base hook' => 'field',
    ],
  );
   * */
  $tt = "ss";
}

function rdasa_mapping_theme_suggestions_alter(array &$suggestions, array $variables, $hook)
{
  if ($hook == "views_view") {
    $id = $variables["view"]->id();
    if ($variables["view"]->id() == "projects_map") {
      $suggestions[] = "views_view__projects_map";
    }
  }
  /**
  if ($hook == "views_view_unformatted") {

  } elseif ($hook == "views_view_fields") {
    if ( == "projects_map") {
      $suggestions[] = "views_view_fields_projects_map";
    }
  }
   * **/
}
